"""二期 Agent 层：研究员/软思路/每日简报/纠错日志/蒸馏候选/LLM审计/列映射

Revision ID: 10eaf9684492
Revises: 6c0c0443dc71
Create Date: 2026-09-23 10:20:27.303866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import tin.db
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10eaf9684492'
down_revision: Union[str, Sequence[str], None] = '6c0c0443dc71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=32), nullable=False),
    sa.Column('varieties', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('created_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('daily_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.Column('variety', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('tone', sa.String(length=16), nullable=True),
    sa.Column('range_low', sa.Float(), nullable=True),
    sa.Column('range_high', sa.Float(), nullable=True),
    sa.Column('range_series_id', sa.String(length=80), nullable=True),
    sa.Column('stance', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('claims', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('playbook_item_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('signal_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('unverified', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('generated_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', tin.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('researcher_id', 'variety', 'trade_date', name='uq_brief_per_day')
    )
    with op.batch_alter_table('daily_briefs', schema=None) as batch_op:
        batch_op.create_index('ix_brief_variety_date', ['variety', 'trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_briefs_researcher_id'), ['researcher_id'], unique=False)

    op.create_table('playbook_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.Column('variety', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('scope', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_ref', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', tin.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playbook_items', schema=None) as batch_op:
        batch_op.create_index('ix_playbook_active', ['researcher_id', 'variety', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_playbook_items_researcher_id'), ['researcher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playbook_items_variety'), ['variety'], unique=False)

    op.create_table('vendor_column_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=32), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('column_name', sa.String(length=128), nullable=False),
    sa.Column('series_id', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confirmed_by', sa.String(length=32), nullable=False),
    sa.Column('confirmed_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_hit_at', tin.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['indicators.series_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint', 'column_name', name='uq_column_map')
    )
    with op.batch_alter_table('vendor_column_maps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_column_maps_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_column_maps_vendor'), ['vendor'], unique=False)

    op.create_table('brief_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=True),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('elapsed_seconds', sa.Integer(), nullable=True),
    sa.Column('distilled', sa.Boolean(), nullable=False),
    sa.Column('created_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['daily_briefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brief_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brief_revisions_brief_id'), ['brief_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brief_revisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_revision_brief', ['brief_id', 'created_at'], unique=False)

    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('request', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('brief_id', sa.Integer(), nullable=True),
    sa.Column('created_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['daily_briefs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_brief_id'), ['brief_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_llm_purpose_at', ['purpose', 'created_at'], unique=False)

    op.create_table('playbook_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.Column('variety', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('scope', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_revision_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('promoted_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', tin.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['promoted_item_id'], ['playbook_items.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playbook_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playbook_candidates_researcher_id'), ['researcher_id'], unique=False)

    with op.batch_alter_table('judgments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('researcher_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_judgments_researcher_id'), ['researcher_id'], unique=False)
        batch_op.create_foreign_key('fk_judgments_researcher', 'researchers', ['researcher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('judgments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_judgments_researcher', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_judgments_researcher_id'))
        batch_op.drop_column('researcher_id')

    with op.batch_alter_table('playbook_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playbook_candidates_researcher_id'))

    op.drop_table('playbook_candidates')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_purpose_at')
        batch_op.drop_index(batch_op.f('ix_llm_calls_created_at'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_brief_id'))

    op.drop_table('llm_calls')
    with op.batch_alter_table('brief_revisions', schema=None) as batch_op:
        batch_op.drop_index('ix_revision_brief')
        batch_op.drop_index(batch_op.f('ix_brief_revisions_created_at'))
        batch_op.drop_index(batch_op.f('ix_brief_revisions_brief_id'))

    op.drop_table('brief_revisions')
    with op.batch_alter_table('vendor_column_maps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_column_maps_vendor'))
        batch_op.drop_index(batch_op.f('ix_vendor_column_maps_fingerprint'))

    op.drop_table('vendor_column_maps')
    with op.batch_alter_table('playbook_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playbook_items_variety'))
        batch_op.drop_index(batch_op.f('ix_playbook_items_researcher_id'))
        batch_op.drop_index('ix_playbook_active')

    op.drop_table('playbook_items')
    with op.batch_alter_table('daily_briefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_briefs_researcher_id'))
        batch_op.drop_index('ix_brief_variety_date')

    op.drop_table('daily_briefs')
    op.drop_table('researchers')
    # ### end Alembic commands ###
