"""一期全表：事实层、判断层、三四期预留、系统

Revision ID: 1bea27df71e9
Revises: 
Create Date: 2026-09-18 18:50:12.714948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import tin.db
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bea27df71e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('derived',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.String(length=32), nullable=False),
    sa.Column('variety', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('as_of', tin.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('inputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('computed_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('derived', schema=None) as batch_op:
        batch_op.create_index('ix_derived_formula_asof', ['formula_id', 'variety', 'trade_date'], unique=False)

    op.create_table('factors',
    sa.Column('factor_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('proxy_series', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('alert_rule', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('factor_id')
    )
    op.create_table('fetch_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fetcher', sa.String(length=32), nullable=False),
    sa.Column('target_date', sa.String(length=10), nullable=False),
    sa.Column('started_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', tin.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('written', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fetch_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fetch_runs_fetcher'), ['fetcher'], unique=False)

    op.create_table('indicators',
    sa.Column('series_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('variety', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('caliber', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=8), nullable=False),
    sa.Column('fetch_mode', sa.String(length=8), nullable=False),
    sa.Column('phase', sa.String(length=4), nullable=False),
    sa.Column('owner', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('is_proxy', sa.Boolean(), nullable=False),
    sa.Column('vendor_code', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('series_id')
    )
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indicators_variety'), ['variety'], unique=False)

    op.create_table('judgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variety', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('written_at', sa.Date(), nullable=False),
    sa.Column('review_period_days', sa.Integer(), nullable=False),
    sa.Column('review_due', sa.Date(), nullable=False),
    sa.Column('contradiction', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('marginal_focus', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('cost_line', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('pricing_power', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('time_dimension', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('survey_notes', sa.Text(), nullable=True),
    sa.Column('whitelist', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('paradigm', sa.String(length=16), nullable=True),
    sa.Column('tone', sa.String(length=16), nullable=True),
    sa.Column('tone_note', sa.Text(), nullable=True),
    sa.Column('thresholds', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('priority_rule', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('falsifiers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('unstructured', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('review_warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('judgments', schema=None) as batch_op:
        batch_op.create_index('uq_judgment_active', ['variety'], unique=True, sqlite_where=sa.text("status = '生效'"), postgresql_where=sa.text("status = '生效'"))
        batch_op.create_index('uq_judgment_version', ['variety', 'version'], unique=True)

    op.create_table('macro_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('regime', sa.String(length=32), nullable=False),
    sa.Column('variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trading_days',
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('year_seq', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('trade_date')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('judgment_factor_link',
    sa.Column('judgment_id', sa.Integer(), nullable=False),
    sa.Column('factor_id', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('weight_hint', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['factor_id'], ['factors.factor_id'], ),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgments.id'], ),
    sa.PrimaryKeyConstraint('judgment_id', 'factor_id')
    )
    op.create_table('judgment_series_refs',
    sa.Column('judgment_id', sa.Integer(), nullable=False),
    sa.Column('ref_type', sa.String(length=16), nullable=False),
    sa.Column('ref_id', sa.String(length=80), nullable=False),
    sa.Column('series_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['indicators.series_id'], ),
    sa.PrimaryKeyConstraint('judgment_id', 'ref_type', 'ref_id')
    )
    with op.batch_alter_table('judgment_series_refs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_judgment_series_refs_series_id'), ['series_id'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('as_of', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('caliber_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('entered_by', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['indicators.series_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'as_of', 'revision')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index('ix_obs_series_asof', ['series_id', 'as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_as_of'), ['as_of'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judgment_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('rule_type', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=8), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('gap_note', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('generated_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_judgment_id'), ['judgment_id'], unique=False)

    op.create_table('review_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judgment_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('assignee', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=8), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', tin.db.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgments.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_tasks_judgment_id'), ['judgment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_tasks_judgment_id'))

    op.drop_table('review_tasks')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_judgment_id'))

    op.drop_table('signals')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_as_of'))
        batch_op.drop_index('ix_obs_series_asof')

    op.drop_table('observations')
    with op.batch_alter_table('judgment_series_refs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_judgment_series_refs_series_id'))

    op.drop_table('judgment_series_refs')
    op.drop_table('judgment_factor_link')
    op.drop_table('users')
    op.drop_table('trading_days')
    op.drop_table('macro_scenarios')
    with op.batch_alter_table('judgments', schema=None) as batch_op:
        batch_op.drop_index('uq_judgment_version')
        batch_op.drop_index('uq_judgment_active', sqlite_where=sa.text("status = '生效'"), postgresql_where=sa.text("status = '生效'"))

    op.drop_table('judgments')
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indicators_variety'))

    op.drop_table('indicators')
    with op.batch_alter_table('fetch_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fetch_runs_fetcher'))

    op.drop_table('fetch_runs')
    op.drop_table('factors')
    with op.batch_alter_table('derived', schema=None) as batch_op:
        batch_op.drop_index('ix_derived_formula_asof')

    op.drop_table('derived')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
