"""Excel 导入导出：指标默认时刻、导出模板、导入暂存

Revision ID: 6c0c0443dc71
Revises: 1bea27df71e9
Create Date: 2026-09-20 17:25:27.886665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import tin.db
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c0c0443dc71'
down_revision: Union[str, Sequence[str], None] = '1bea27df71e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variety', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('columns', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('date_range', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('sort_order', sa.String(length=16), nullable=False),
    sa.Column('created_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_templates_variety'), ['variety'], unique=False)
        batch_op.create_index('uq_export_template_default', ['variety'], unique=True, sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default = TRUE'))

    op.create_table('import_previews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('variety', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_previews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_previews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_previews_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_previews_variety'), ['variety'], unique=False)

    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_entry_time', sa.Time(), nullable=True))

    # seed_indicators() 只补缺失指标、不覆盖已有记录，已有库需在此显式回填
    for series_id, at in (("SMM.SN.spot.1", "11:30:00"),
                          ("MYSTEEL.SN.TC.YN40", "11:00:00"),
                          ("MYSTEEL.SN.stock.social", "15:00:00"),
                          ("LME.SN.stock", "19:00:00")):
        op.execute(sa.text("UPDATE indicators SET default_entry_time = :at WHERE series_id = :sid")
                   .bindparams(at=at, sid=series_id))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_column('default_entry_time')

    with op.batch_alter_table('import_previews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_previews_variety'))
        batch_op.drop_index(batch_op.f('ix_import_previews_expires_at'))
        batch_op.drop_index(batch_op.f('ix_import_previews_created_at'))

    op.drop_table('import_previews')
    with op.batch_alter_table('export_templates', schema=None) as batch_op:
        batch_op.drop_index('uq_export_template_default', sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default = TRUE'))
        batch_op.drop_index(batch_op.f('ix_export_templates_variety'))

    op.drop_table('export_templates')
    # ### end Alembic commands ###
