"""简报基调附注 + 信号每日唯一约束

Revision ID: 794490950747
Revises: 10eaf9684492
Create Date: 2026-09-23 11:00:55.035000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import tin.db


# revision identifiers, used by Alembic.
revision: str = '794490950747'
down_revision: Union[str, Sequence[str], None] = '10eaf9684492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_briefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tone_note', sa.Text(), nullable=True))

    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_signal_per_day', ['judgment_id', 'rule_id', 'trade_date'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_constraint('uq_signal_per_day', type_='unique')

    with op.batch_alter_table('daily_briefs', schema=None) as batch_op:
        batch_op.drop_column('tone_note')

    # ### end Alembic commands ###
