"""diagram_templates

Revision ID: 97707b0ebd62
Revises: 6c0c0443dc71
Create Date: 2026-09-23 09:57:14.064471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import tin.db
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97707b0ebd62'
down_revision: Union[str, Sequence[str], None] = '6c0c0443dc71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagram_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variety', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('layout', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', tin.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagram_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagram_templates_variety'), ['variety'], unique=False)
        batch_op.create_index('uq_diagram_template_default', ['variety'], unique=True, sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default = TRUE'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagram_templates', schema=None) as batch_op:
        batch_op.drop_index('uq_diagram_template_default', sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default = TRUE'))
        batch_op.drop_index(batch_op.f('ix_diagram_templates_variety'))

    op.drop_table('diagram_templates')
    # ### end Alembic commands ###
